### ISSUE TITLE
Can use in ViewModel?

### ISSUE THREAD

**Issue by JakeWoki** [uber/AutoDispose#110]
[ViewModel](https://developer.android.com/topic/libraries/architecture/viewmodel.html)

**Comment by hzsweers** [comment]
Can you please elaborate? I can't tell if this is a feature request or general implementation question

**Comment by JakeWoki** [comment]
[android-architecture-components](https://github.com/googlesamples/android-architecture-components/tree/master/BasicRxJavaSample)
Like this.If use Rx subscriptions in [ViewModel](https://developer.android.com/topic/libraries/architecture/viewmodel.html) and to stop in response to `OnLifecycleEvent`,can use `AutoDispose` to stop?

**Comment by hzsweers** [comment]
Are you asking for support for that or if it's possible?  For the latter, you could make one that scopes to `onCleared()` for internal loads. That said, the examples there indicate what I would agree is the correct approach as well: expose APIs that return RxJava types and scope them when they're used. That's why I don't think we should make a first-party component either. The ViewModel should just be an orchestration layer between the UI and data source, not *be* the data source.

See https://github.com/googlesamples/android-architecture-components/blob/master/BasicRxJavaSample/app/src/main/java/com/example/android/observability/ui/UserViewModel.java#L48-L56

**Comment by blackberry2016** [comment]
@JakeWoki Yes , you can, but bad idea. I had done in version 0.2.0 
And now i prefer to 
``` java
compile 'com.uber.autodispose:autodispose-android-archcomponents:x.y.z'
```

**Comment by JakeWoki** [comment]
@blackberry2016 
How to use?use in ViewModel or Activity/Fragment...?

**Comment by hzsweers** [comment]
@JakeWoki please see the sample for activity/fragment examples. I'm going to close this out one
