### ISSUE TITLE
Proposal: Add test() helper to subscribe proxies

### ISSUE THREAD

**Issue by hzsweers** [uber/AutoDispose#137]
This is a pretty convenient function and we could just add a convenience shorthand for it.

**Comment by VisheshVadhera** [comment]
Hey I would love to close this one next. Can you please tell me what the `test()` function would look like? I believe the main use case would be to help in testing?

**Comment by hzsweers** [comment]
Yep it would just mirror the `test()` methods in RxJava types and return a `TestObserver`. Should be pretty simple, but is a nice usability improvement for consumers. We can "test" it by migrating tests here to use it where appropriate.

**Comment by hzsweers** [comment]
@VisheshVadhera did you still want to do this? Was thinking of cutting 0.6.0 soon-ish

**Comment by VisheshVadhera** [comment]
This one is almost ready. Just need to move the tests to use the subscribe
proxies' test() methods to get TestObservers & TestSubscribers.

Hopefully, I should be able to open the PR tonight.

On Jan 16, 2018 8:16 AM, "Zac Sweers" <notifications@github.com> wrote:

@VisheshVadhera <https://github.com/visheshvadhera> did you still want to
do this? Was thinking of cutting 0.6.0 soon-ish

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/uber/AutoDispose/issues/137#issuecomment-357838570>,
or mute
the thread

**Comment by hzsweers** [comment]
sounds good :+1:
