### ISSUE TITLE
1.1.0-SNAPSHOT Suggestion: reword Lint error to be more clear

### ISSUE THREAD

**Issue by ParthPadg** [uber/AutoDispose#314]
The lint short-text in the 1.1.0 snapshot is a bit confusing. 

Currently, it is `Always apply an AutoDispose scope before subscribing within defined scoped elements.`, which I think is going to confuse a lot of people, especially if they don't think about Rx streams/subscriptions in terms of "scopes" (I know I don't!). 

Suggested rewrite: `Missing Disposable handling: Apply AutoDispose or cache the Disposable instance manually`

PS: I don't know if it's intentional, but `val d = Observable.just(1).subscribe()` causes a linting error; however, as far as Lint should concerned, everything is being handled correctly. Just my 2 cents. 

PPS: the long text has a typo -- `handling it's subscription` should be `handling its subscription`

**Comment by hzsweers** [comment]
So for `val d = Observable.just(1).subscribe()`, you can have that by enabling lenient mode: https://github.com/uber/AutoDispose/wiki/Lint-Check

But yeah we can definitely improve the message a bit for the lint and error prone checker. @shaishavgandhi05 want to take a look at this?

**Comment by shaishavgandhi05** [comment]
We can include the lint wiki in the changelog to make sure that the lenient mode is discovered.

**Comment by shaishavgandhi05** [comment]
@ParthPadg How about `Missing Disposable handling: Apply AutoDispose or cache the Disposable instance manually and enable lenient mode.`

The expanded message then looks something like this:
`You're subscribing to an observable but not handling its subscription. This can result in memory leaks. You can avoid memory leaks by appending ".as(autoDisposable(this))" before you subscribe or cache the Disposable instance manually and enable lenient mode. More: https://github.com/uber/AutoDispose/wiki/Lint-Check`

Will also change the error-prone checker to have the same message. Since EP already provides the wiki link, we're covered there. 

Thoughts?

**Comment by ParthPadg** [comment]
I missed the boat, but I like that suggestion, so 👍
