### ISSUE TITLE
Lint Check with RxBinding  Conflict

### ISSUE THREAD

**Issue by liangjingkanji** [uber/AutoDispose#323]
i don't requirement lint check 

how do close it

**Comment by shaishavgandhi05** [comment]
There technically isn't any conflict since RxBinding also exposes Observable's whose subscriptions should be handled safely.

If you're already handling those subscriptions by capturing a `Disposable` like:
```kotlin
fun bindViews() {
  val disposable = RxView.clicks(button).subscribe()  
}
```
consider enabling `lenient` mode for AutoDispose by adding  in your `gradle.properties` file. 
```
autodispose.lenient=true
```

If you want to disable lint fully, there are a few options as prescribed in the [Android documentation](https://developer.android.com/studio/write/lint#gradle). You can choose to disable certain checks also.

**Comment by hzsweers** [comment]
Yep, if you feel it's wrong then please file a bug with an example code that's wrong.

**Comment by liangjingkanji** [comment]
thank you
