### ISSUE TITLE
AndroidLifecycleScopeProvider didn't commit last event when acitivity was re-started

### ISSUE THREAD

**Issue by yhd4711499** [uber/AutoDispose#410]
version: 1.4.0
code:
```
// activity was stopped

doSomeNetworkRequest()
            .observeOn(mainThread())
            .autoDispose(this /*an acitivy*/)
            .subscribe({
                // expected: got last event when activity was brought back to foregound
                // actual: the subscription was disposed when LifecycleEventsObservable received an ending event, which is ON_STOP by default
            }, {
                
            })
```

The problem can be fixed by adding `Event.ON_DESTROY` as the `untilEvent`. It's not a problem actually but I can't understand why `Event.ON_DESTROY` is not the default `untilEvent` since the usecase above is quite common.

**Comment by ShaishavGandhi** [comment]
This is working as intended. 

`Event.ON_DESTROY` isn't the default because users will want to stop their stream at different times depending on their architecture and use-case. AutoDispose doesn't want to be opinionated on when you should dispose your streams.

If you don't specify an `untilEvent`, then AutoDispose tries to infer where you subscribed to your stream and finds the corresponding end-lifecycle event. I believe that's what's happening in your case.
